default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000
  username: <%= ENV["USERNAME"] %>
  password: <%= ENV["PASSWORD"] %>

development:
  <<: *default
  database: line-chart

test:
  <<: *default
  database: line-chart-test

production:
  <<: *default
